FORBIDDEN_WORDS = [
    "idiota",
    "imbecil",
    "estupido",
    "tonto",
    "ofensa",
    "odio",
    "racista",
    "discriminacion",
    "terrorismo",
    "violacion",
    "asesinato",
    "arma",
    "droga",
    "suicidio",
    "pornografia",
    "contenido sexual",
    "acoso",
    "insulto",
    "spam",
    "fraude",
    "xxx",
]