"""change colum name on post_tags

Revision ID: f3df9aee6c53
Revises: 6a3d0737d211
Create Date: 2025-10-28 11:46:38.252668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3df9aee6c53'
down_revision: Union[str, Sequence[str], None] = '6a3d0737d211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_tags', sa.Column('post_id', sa.Integer(), nullable=False))
    op.add_column('post_tags', sa.Column('tag_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('post_tags_tag.id_fkey'), 'post_tags', type_='foreignkey')
    op.drop_constraint(op.f('post_tags_post.id_fkey'), 'post_tags', type_='foreignkey')
    op.create_foreign_key(None, 'post_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'post_tags', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_column('post_tags', 'post.id')
    op.drop_column('post_tags', 'tag.id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_tags', sa.Column('tag.id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('post_tags', sa.Column('post.id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'post_tags', type_='foreignkey')
    op.drop_constraint(None, 'post_tags', type_='foreignkey')
    op.create_foreign_key(op.f('post_tags_post.id_fkey'), 'post_tags', 'posts', ['post.id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('post_tags_tag.id_fkey'), 'post_tags', 'tags', ['tag.id'], ['id'], ondelete='CASCADE')
    op.drop_column('post_tags', 'tag_id')
    op.drop_column('post_tags', 'post_id')
    # ### end Alembic commands ###
